---
title: "Metrics"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "Richard Wen <richard.wen@unityhealth.to>"
output: html_notebook
---

```{r, echo=FALSE}
knitr::opts_chunk$set(
  message=FALSE,
  warning=FALSE
)
```

## Libraries

```{r}
library(tidyverse)

options(readr.show_col_types = FALSE)
```

## Functions

Functions for PCCC and CSMF Accuracy.

```{r}
calc_pccc <- function(actual, pred, k = 1, N = NULL) {
    
    # Calc N num of causes if not known
    N <- if (is.null(N)) length(unique(c(actual, pred))) else N
    
    # Calc frac of deaths in top k causes
    C <- sum(actual == pred) / len(actual)
    
    # Calc PCCC
    out <- (C - (k/N)) / (1 - (k/N))
    return(out)
}

calc_csmf_acc <- function(actual, pred) {
    
    # Get all unique causes
    causes <- unique(c(actual, pred))
    
    # Get csmfs
    cases <- length(actual)
    csmf_true <- table(actual) / cases
    csmf_pred <- table(pred) / cases
    
    # Correct for missing causes in either actual or pred
    csmf_true <- vapply(
        causes,
        function(x) if (x %in% names(csmf_true)) csmf_true[x] else 0,
        FUN.VALUE = numeric(1)
    )
    csmf_pred <- vapply(
        causes,
        function(x) if (x %in% names(csmf_pred)) csmf_pred[x] else 0,
        FUN.VALUE = numeric(1)
    )
    
    # Calc csmf max error
    csmf_max_error <- 2 * (1 - min(csmf_true))
    
    # Calc csmf acc
    out <- 1 - (sum(abs(csmf_true - csmf_pred)) / csmf_max_error)
    return(out)
}
```

## Data

Load data from `data` and `tmp` folders.

```{r}
df <- list(
    wva2016_icd10 = read_csv(
        "../data/wva2016_icd10_v1.csv",
        col_types = cols(wva2016_code = col_double())
    ),
    icd10_cghr10 = read_csv("../data/icd10_cghr10_v1.csv"),
    ages = bind_rows(
        read_csv(
            "../tmp/healsl_rd1_adult_v1.csv",
            col_select = "rowid"
        ) %>% mutate(round = 1, age = "adult"),
        read_csv(
            "../tmp/healsl_rd2_adult_v1.csv",
            col_select = "rowid"
        ) %>% mutate(round = 2, age = "adult"),
        read_csv(
            "../tmp/healsl_rd1_child_v1.csv",
            col_select = "rowid"
        ) %>% mutate(round = 1, age = "child"),
        read_csv(
            "../tmp/healsl_rd2_child_v1.csv",
            col_select = "rowid"
        ) %>% mutate(round = 2, age = "child"),
        read_csv(
            "../tmp/healsl_rd1_neo_v1.csv",
            col_select = "rowid"
        ) %>% mutate(round = 1, age = "neo"),
        read_csv(
            "../tmp/healsl_rd2_neo_v1.csv",
            col_select = "rowid"
        ) %>% mutate(round = 2, age = "neo")
    ),
    model_chatgpt3 = bind_rows(
        read_csv(
            "../tmp/healsl_rd1_rapid_chatgpt3_v1.csv",
            col_select = c("rowid", "round", "api_chat_icd")
        ),
        read_csv(
            "../tmp/healsl_rd2_rapid_chatgpt3_v1.csv",
            col_select = c("rowid", "round", "api_chat_icd")
        )
    ) %>% rename(chatgpt3_icd10 = api_chat_icd),
    model_chatgpt4 = bind_rows(
        read_csv(
            "../tmp/healsl_rd1_rapid_chatgpt4_v1.csv",
            col_select = c("rowid", "round", "api_chat_icd")
        ),
        read_csv(
            "../tmp/healsl_rd2_rapid_chatgpt4_v1.csv",
            col_select = c("rowid", "round", "api_chat_icd")
        )
    ) %>% rename(chatgpt4_icd10 = api_chat_icd),
    model_insilicova = bind_rows(
        read_csv(
            "../tmp/healsl_rd1_rapid_insilicova_v1.csv",
            col_select = c("rowid", "round", "cause1_wva")
        ),
        read_csv(
            "../tmp/healsl_rd2_rapid_insilicova_v1.csv",
            col_select = c("rowid", "round", "cause1_wva")
        )
    ) %>% rename(insilicova_wva2016 = cause1_wva),
    model_interva5 = bind_rows(
        read_csv(
            "../tmp/healsl_rd1_rapid_interva5_v1.csv",
            col_select = c("rowid", "round", "cause1_wva")
        ),
        read_csv(
            "../tmp/healsl_rd2_rapid_interva5_v1.csv",
            col_select = c("rowid", "round", "cause1_wva")
        )
    ) %>% rename(interva5_wva2016 = cause1_wva)
)
```

```{r, echo=FALSE}
for (i in names(df)) {
    print(i)
    print(head(df[[i]]))
}
```

## Preprocess

Combine all model predictions with their ages.

```{r}
models <- df[str_starts(names(df), "model_")]
models$all <- df$ages
for (i in 1:length(models)) {
    models$all <- models$all %>%
        left_join(
            models[[i]],
            by = c("rowid" = "rowid", "round" = "round"),
            suffix = c("", "")
        )
}
head(models$all)
```

Convert ICD-10 and WVA-2016 codes to CGHR-10 codes.

```{r}

# Get wva2016 cols for model preds
wva_cols <- colnames(models$all)
wva_cols <- wva_cols[!wva_cols %in% c("rowid", "round", "age")]
wva_cols <- wva_cols[str_ends(wva_cols, "_wva2016")]

# Convert wva2016 to icd10 via join
for (wcol in wva_cols) {
    
    # Create new converted col based on model name
    mname <- str_remove(wcol, "_wva2016")
    iname <- paste0(mname, "_icd10")
    
    # Join model wva to mapping wva
    models$all <- models$all %>%
    left_join(
        df$wva2016_icd10 %>%
            select(wva2016_code, icd10_code) %>%
            rename_with(~iname, icd10_code),
        by = setNames("wva2016_code", wcol),
        multiple = "first"
    )
}

# Get icd10 cols for model preds
icd_cols <- colnames(models$all)
icd_cols <- icd_cols[!icd_cols %in% c("rowid", "round", "age")]
icd_cols <- icd_cols[str_ends(icd_cols, "_icd10")]

# Convert icd10 to cghr10 via join
for (icol in icd_cols) {
    
    # Create new converted col based on model name
    mname <- str_remove(icol, "_icd10")
    cname <- paste0(mname, "_cghr10")
    
    # Remove all whitespaces and keep only first icd10 code if multiple
    models$all[[icol]] <- str_replace_all(models$all[[icol]], "\\s", "")
    models$all[[icol]] <- str_extract(models$all[[icol]], "^[A-Za-z]\\d{2}")
    
    # Join model wva to mapping wva
    models$all <- models$all %>%
    left_join(
        df$icd10_cghr10 %>%
            select(icd10_code, cghr10_title, cghr10_age) %>%
            rename_with(~cname, cghr10_title),
        by = setNames(c("icd10_code", "cghr10_age"), c(icol, "age")),
        multiple = "first"
    )
}

head(models$all)
```